# Generated by Django 6.0.2 on 2026-06-12 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('agency', 'Agency')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posts_por_mes', models.PositiveIntegerField(help_text='Límite de contenidos generados por mes')),
                ('stripe_price_id', models.CharField(blank=True, help_text='price_xxx de Stripe', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de presentación en pricing')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('trial', 'Trial'), ('activo', 'Activo'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido'), ('pago_fallido', 'Pago fallido')], default='trial', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('trial_fin', models.DateTimeField(blank=True, null=True)),
                ('periodo_actual_fin', models.DateTimeField(blank=True, null=True)),
                ('posts_generados_mes', models.PositiveIntegerField(default=0)),
                ('posts_reset_fecha', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.plan')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
