# Generated by Django 6.0.2 on 2026-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio_clp',
            field=models.PositiveIntegerField(default=0, help_text='Precio en pesos chilenos (CLP) para mostrar en la interfaz'),
        ),
    ]
