# Generated by Django 6.0.2 on 2026-05-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de conocimiento',
                'verbose_name_plural': 'Categorías de conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversación IA',
                'verbose_name_plural': 'Conversaciones IA',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaAprendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta_sugerida', models.TextField(blank=True)),
                ('respondida', models.BooleanField(default=False)),
                ('veces_preguntada', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta aprendida',
                'verbose_name_plural': 'Preguntas aprendidas',
                'ordering': ['-veces_preguntada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='agente_ia.conversacionagente')),
            ],
            options={
                'verbose_name': 'Mensaje IA',
                'verbose_name_plural': 'Mensajes IA',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('palabras_clave', models.TextField(help_text='Separar palabras clave con coma')),
                ('respuesta', models.TextField()),
                ('prioridad', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('veces_utilizada', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='agente_ia.categoriaconocimiento')),
            ],
            options={
                'verbose_name': 'Respuesta IA',
                'verbose_name_plural': 'Respuestas IA',
                'ordering': ['-prioridad', 'titulo'],
            },
        ),
    ]
