# Generated by Django 6.0 on 2026-02-23 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del contacto.', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('empresa', models.CharField(blank=True, max_length=160)),
                ('asunto', models.CharField(blank=True, max_length=160)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_gestion', 'En gestión'), ('cotizado', 'Cotizado'), ('cerrado', 'Cerrado'), ('perdido', 'Perdido')], db_index=True, default='nuevo', max_length=24)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Ejecutivo asignado al lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Empresa/Workspace dueño del lead (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='LeadAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('stage_changed', 'Cambio de etapa'), ('owner_changed', 'Reasignación'), ('note_added', 'Nota agregada'), ('updated', 'Actualización')], db_index=True, max_length=40)),
                ('message', models.CharField(blank=True, max_length=240)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_audit_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='crm.lead')),
                ('workspace', models.ForeignKey(help_text='Workspace relacionado al evento (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'estado', 'fecha_creacion'], name='crm_lead_workspa_ea461b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'updated_at'], name='crm_lead_workspa_a0b337_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'email'], name='crm_lead_workspa_8bba31_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'empresa'], name='crm_lead_workspa_2f8f01_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'owner'], name='crm_lead_workspa_43daf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('workspace', 'email'), name='uniq_lead_email_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['workspace', 'created_at'], name='crm_leadaud_workspa_471cec_idx'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['lead', 'created_at'], name='crm_leadaud_lead_id_f1a0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['action'], name='crm_leadaud_action_91a0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', 'created_at'], name='crm_leadnot_lead_id_1321d1_idx'),
        ),
    ]
