# Generated by Django 6.0.2 on 2026-02-23 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_review', 'En revisión'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('discarded', 'Descartado')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('converted_to_lead', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_demo_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='public_demo_status_66f3e6_idx'), models.Index(fields=['email'], name='public_demo_email_f1dfd7_idx')],
            },
        ),
    ]
