# Generated by Django 6.0.2 on 2026-02-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='crm.lead'),
        ),
    ]
