# Generated by Django 6.0.2 on 2026-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_demorequest_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Resumen corto para listado y SEO', max_length=300)),
                ('content', models.TextField(help_text='Contenido completo del artículo en HTML')),
                ('meta_title', models.CharField(blank=True, help_text='Título SEO (máx 70 caracteres)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Descripción SEO (máx 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, help_text='Ej: Automatización, Software, IA', max_length=80)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Destacar en la landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['published', 'published_at'], name='public_blog_publish_c923ac_idx'), models.Index(fields=['slug'], name='public_blog_slug_9866a1_idx')],
            },
        ),
    ]
