# Generated by Django 6.0.2 on 2026-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='nurturing_dia14_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='nurturing_dia3_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='nurturing_dia7_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
