# Generated by Django 6.0.2 on 2026-06-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaNexa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rubro', models.CharField(help_text='Sector o industria de la empresa', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción general del negocio')),
                ('publico_objetivo', models.TextField(help_text='A quién va dirigida la empresa')),
                ('tono_marca', models.CharField(choices=[('profesional', 'Profesional'), ('cercano', 'Cercano y amigable'), ('inspirador', 'Inspirador'), ('humoristico', 'Humorístico'), ('exclusivo', 'Exclusivo / Premium'), ('educativo', 'Educativo')], default='profesional', max_length=50)),
                ('objetivo_principal', models.CharField(choices=[('ventas', 'Aumentar ventas'), ('reconocimiento', 'Reconocimiento de marca'), ('comunidad', 'Construir comunidad'), ('educacion', 'Educar al mercado'), ('confianza', 'Generar confianza')], default='ventas', max_length=50)),
                ('instagram', models.CharField(blank=True, help_text='Usuario de Instagram sin @', max_length=100)),
                ('sitio_web', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa (PNG o JPG recomendado)', null=True, upload_to='nexa/logos/')),
                ('color_principal', models.CharField(default='#3b82f6', help_text='Color hexadecimal principal, ej: #3b82f6', max_length=7)),
                ('color_secundario', models.CharField(default='#8b5cf6', help_text='Color hexadecimal secundario, ej: #8b5cf6', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario propietario de esta empresa en Nexa', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_nexa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa Nexa',
                'verbose_name_plural': 'Empresas Nexa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('carrusel', 'Carrusel'), ('historia', 'Historia'), ('post', 'Post'), ('reel', 'Reel'), ('campana', 'Campaña')], max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('copy', models.TextField(help_text='Texto principal del contenido')),
                ('hashtags', models.TextField(blank=True, help_text='Hashtags separados por espacio')),
                ('cta', models.CharField(blank=True, help_text='Call to action del contenido', max_length=200)),
                ('estructura_json', models.JSONField(default=dict, help_text='Estructura detallada del contenido (diapositivas, escenas, stickers, etc.)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('programado', 'Programado'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(help_text='Empresa para la que se generó este contenido', on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='nexa.empresanexa')),
            ],
            options={
                'verbose_name': 'Contenido Generado',
                'verbose_name_plural': 'Contenidos Generados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MemoriaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propuesta_valor', models.TextField(help_text='Qué hace única a esta empresa frente a la competencia')),
                ('servicios_principales', models.TextField(help_text='Lista de servicios o productos principales, uno por línea')),
                ('palabras_clave', models.TextField(help_text='Palabras clave de marca separadas por coma')),
                ('estilo_comunicacion', models.TextField(help_text='Cómo se comunica la marca con su audiencia')),
                ('evitar_mencionar', models.TextField(blank=True, help_text='Temas, palabras o frases que la marca NO debe usar')),
                ('instrucciones_ia', models.TextField(blank=True, help_text='Instrucciones especiales para los agentes IA (contexto extra, restricciones)')),
                ('resumen_marca', models.TextField(blank=True, help_text='Resumen ejecutivo de la marca — generado o editado para uso en prompts IA')),
                ('empresa', models.OneToOneField(help_text='Empresa a la que pertenece esta memoria de marca', on_delete=django.db.models.deletion.CASCADE, related_name='memoria_marca', to='nexa.empresanexa')),
            ],
            options={
                'verbose_name': 'Memoria de Marca',
                'verbose_name_plural': 'Memorias de Marca',
            },
        ),
        migrations.AddIndex(
            model_name='empresanexa',
            index=models.Index(fields=['usuario'], name='nexa_empres_usuario_19799b_idx'),
        ),
        migrations.AddIndex(
            model_name='contenidogenerado',
            index=models.Index(fields=['empresa', 'estado'], name='nexa_conten_empresa_0ac311_idx'),
        ),
        migrations.AddIndex(
            model_name='contenidogenerado',
            index=models.Index(fields=['fecha_creacion'], name='nexa_conten_fecha_c_0d3265_idx'),
        ),
    ]
