# Generated by Django 6.0.2 on 2026-06-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrategiaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField(help_text='Objetivo principal de la estrategia mensual')),
                ('pilares_contenido', models.TextField(help_text='Pilares temáticos de contenido separados por coma')),
                ('frecuencia_publicacion', models.CharField(help_text='Frecuencia recomendada de publicación, ej: 3 veces por semana', max_length=100)),
                ('publico_objetivo', models.TextField(help_text='Público objetivo específico para este mes')),
                ('calendario_json', models.JSONField(default=dict, help_text='Calendario semanal generado: 4 semanas con tipos y temas de contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(help_text='Empresa para la que se generó esta estrategia', on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='nexa.empresanexa')),
            ],
            options={
                'verbose_name': 'Estrategia Mensual',
                'verbose_name_plural': 'Estrategias Mensuales',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empresa'], name='nexa_estrat_empresa_6daf00_idx')],
            },
        ),
    ]
