# Generated by Django 6.0.2 on 2026-06-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0002_estrategiamensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidogenerado',
            name='estrategia',
            field=models.ForeignKey(blank=True, help_text='Estrategia mensual que originó este contenido (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos', to='nexa.estrategiamensual'),
        ),
    ]
