# Generated by Django 6.0.2 on 2026-06-04 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0003_contenidogenerado_estrategia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatividadInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('post', 'Post'), ('historia', 'Historia'), ('carrusel', 'Carrusel'), ('reel', 'Reel')], max_length=20)),
                ('prompt_visual', models.TextField(help_text='Prompt profesional listo para enviar a OpenAI Images / Flux / Ideogram / Gemini')),
                ('estructura_visual_json', models.JSONField(default=dict, help_text='Especificación visual completa: colores, slides, escenas, elementos de diseño')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('aprobada', 'Aprobada'), ('publicada', 'Publicada')], default='generada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(help_text='Contenido generado a partir del cual se creó esta creatividad', on_delete=django.db.models.deletion.CASCADE, related_name='creatividades', to='nexa.contenidogenerado')),
            ],
            options={
                'verbose_name': 'Creatividad Instagram',
                'verbose_name_plural': 'Creatividades Instagram',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['contenido', 'tipo'], name='nexa_creati_conteni_a7a335_idx')],
            },
        ),
    ]
