# Generated by Django 6.0.2 on 2026-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0004_creatividadinstagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatividadinstagram',
            name='render_css',
            field=models.TextField(blank=True, help_text='CSS scoped del render — permite personalización por creatividad'),
        ),
        migrations.AddField(
            model_name='creatividadinstagram',
            name='render_html',
            field=models.TextField(blank=True, help_text='HTML renderizado del mockup — reemplazar por imagen real cuando se active la API de generación'),
        ),
    ]
