# Generated by Django 6.0.2 on 2026-06-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0005_creatividadinstagram_render_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatividadinstagram',
            name='veces_regenerada',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que fue regenerada desde su creación inicial'),
        ),
    ]
