# Generated by Django 6.0.2 on 2026-06-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0006_add_veces_regenerada_to_creatividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatividadinstagram',
            name='estilo',
            field=models.CharField(blank=True, default='', help_text='ID del estilo creativo aplicado (corporate_kpi, minimalista_premium, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='creatividadinstagram',
            name='estilo_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre legible del estilo creativo', max_length=100),
        ),
    ]
