# Generated by Django 6.0.2 on 2026-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0007_add_estilo_to_creatividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatividadinstagram',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que fue generada o regenerada — usado para anti-repetición de estilos'),
        ),
    ]
